---
title: "data manipulation"
output: github_document
---

```{r setup, echo=FALSE, message=FALSE}
library(tidyverse)
```

This document will show how to *manipulate* data.

```{r}
litters_df = 
    read_csv("./data_import_examples/FAS_litters.csv", na = c("NA", ".", ""))

litters_df = 
    janitor::clean_names(litters_df)

pups_df = 
    read_csv("./data_import_examples/FAS_pups.csv", na = c("NA", "."))

pups_df = 
    janitor::clean_names(pups_df)
```

## 'select'
Use 'select()' to select variables
```{r}
select(litters_df, group, litter_number, gd0_weight, pups_born_alive)
```

```{r}
select(litters_df, group:gd_of_birth)

select(litters_df, -pups_survive)
```

```{r}
select(litters_df, starts_with('gd'))

select(litters_df, contains('pups'))
```

```{r}
select(litters_df, GROUP=group)

rename(litters_df, GROUP=group)

select(litters_df, litter_number, pups_survive, everything())

relocate(litters_df, litter_number, pups_survive)
```

## 'filter'

```{r}
filter(litters_df, gd_of_birth == 20)
filter(litters_df, pups_born_alive > 8)
filter(litters_df, !(pups_survive == 4))

filter(litters_df, group == 'Low8') 
filter(litters_df, group %in% c('Low8','Low7'))

filter(litters_df, group %in% c('Low8','Low7'), pups_born_alive == 8)
```

```{r}
drop_na(litters_df)

drop_na(litters_df, gd0_weight)
```

```{r}
filter(pups_df, sex == 1)
filter(pups_df, sex == 2, pd_walk < 11)
```

## 'mutate'

```{r}
mutate(litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)

mutate(litters_df, sq_pups=pups_born_alive^2)
```

```{r}
mutate(pups_df, pd_sum = pd_ears + pd_eyes + pd_pivot + pd_walk)
```

## 'arrange'
```{r}
arrange(litters_df, gd0_weight)
arrange(litters_df, desc(gd0_weight))

#先根据写在前面的变量排
head(arrange(litters_df, group, pups_born_alive), 10)
```

## Piping!!!

```{r}
litters_df = 
  read_csv("./data_import_examples/FAS_litters.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  select(-pups_survive) |> 
  filter(group=='Low7') |>
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) |> 
  drop_na(wt_gain)

litters_df

#write_csv(litters_df, 'data_import_examples/cleaned_fas_litters.csv')
```

```{r}
litters_df |>
  lm(wt_gain ~ pups_born_alive, data = _) |>
  broom::tidy()
#broom::tidy()将线性模型的结果整理成一个整洁的数据框
```

```{r}
pups_df = 
  read_csv("./data_import_examples/FAS_pups.csv", na = c("NA", ".")) |>
  janitor::clean_names() |> 
  filter(sex == 1) |> 
  select(-pd_ears) |> 
  mutate(pd_pivot_gt7 = pd_pivot >= 7)
```

